# Generated by Django 5.2.7 on 2025-10-29 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('stars', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('name_with_owner', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField()),
                ('forks', models.IntegerField()),
                ('watchers', models.IntegerField()),
                ('issues', models.IntegerField()),
                ('pull_requests', models.IntegerField()),
                ('disk_usage_kb', models.BigIntegerField()),
                ('assignable_user_count', models.IntegerField()),
                ('default_branch_commit_count', models.IntegerField()),
                ('is_fork', models.BooleanField()),
                ('is_archived', models.BooleanField()),
                ('forking_allowed', models.BooleanField(default=True)),
                ('code_of_conduct', models.CharField(blank=True, max_length=100, null=True)),
                ('license', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField()),
                ('pushed_at', models.DateTimeField()),
                ('primary_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_repos', to='app.language')),
                ('topics', models.ManyToManyField(related_name='repositories', to='app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.BigIntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.language')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_languages', to='app.repository')),
            ],
        ),
    ]
