# Generated by Django 5.2.7 on 2025-11-27 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorylanguage',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='repositorylanguage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='stars',
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'unique_together': {('login',)},
            },
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_with_owner', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField(db_index=True)),
                ('forks', models.IntegerField()),
                ('watchers', models.IntegerField()),
                ('is_fork', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('disk_usage_kb', models.IntegerField(null=True)),
                ('pull_requests', models.IntegerField(null=True)),
                ('issues', models.IntegerField(null=True)),
                ('primary_language', models.CharField(db_index=True, max_length=100, null=True)),
                ('language_count', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('pushed_at', models.DateTimeField(db_index=True, null=True)),
                ('default_branch_commit_count', models.IntegerField(null=True)),
                ('license', models.CharField(db_index=True, max_length=255, null=True)),
                ('assignable_user_count', models.IntegerField(null=True)),
                ('code_of_conduct', models.CharField(max_length=255, null=True)),
                ('forking_allowed', models.BooleanField(null=True)),
                ('created_year', models.IntegerField(db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='app.owner')),
            ],
        ),
        migrations.CreateModel(
            name='RepoLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.BigIntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.language')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_languages', to='app.repo')),
            ],
        ),
        migrations.CreateModel(
            name='RepoTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_topics', to='app.repo')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topic')),
            ],
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
        migrations.DeleteModel(
            name='RepositoryLanguage',
        ),
        migrations.AddIndex(
            model_name='repo',
            index=models.Index(fields=['created_year', 'primary_language'], name='app_repo_created_6bb857_idx'),
        ),
        migrations.AddIndex(
            model_name='repo',
            index=models.Index(fields=['primary_language', '-stars'], name='app_repo_primary_4addb1_idx'),
        ),
        migrations.AddIndex(
            model_name='repolanguage',
            index=models.Index(fields=['language', 'repo'], name='app_repolan_languag_ad2655_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repolanguage',
            unique_together={('repo', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='repotopic',
            unique_together={('repo', 'topic')},
        ),
    ]
