# Generated by Django 5.2.7 on 2025-11-28 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_repositorylanguage_repository_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='repo',
            new_name='app_repo_created_734513_idx',
            old_name='app_repo_created_6bb857_idx',
        ),
        migrations.RenameIndex(
            model_name='repo',
            new_name='app_repo_primary_7e8412_idx',
            old_name='app_repo_primary_4addb1_idx',
        ),
        migrations.AlterField(
            model_name='repo',
            name='created_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='created_year',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='forks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repo',
            name='primary_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_repos', to='app.language'),
        ),
        migrations.AlterField(
            model_name='repo',
            name='stars',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='repo',
            name='watchers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repolanguage',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
